import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
let MAP;

const qs=new URLSearchParams(location.search);
const id=qs.get('id')||location.pathname.split('/').filter(Boolean).pop();
const apiBase=(window.ARENA_API_BASE||'https://carlos-4rxr.onrender.com').replace(/\/$/,'');
const ASSET_BASE=(window.CARLOS_ASSET_BASE||new URL('.', location.href).href).replace(/\/$/,'');
const api=()=>`${apiBase}/api/aposta/${encodeURIComponent(id)}?viewer=${encodeURIComponent(getViewer())}`;
let viewer=localStorage.getItem('carlos-arena-viewer'); if(!viewer){viewer=Math.random().toString(36).slice(2);localStorage.setItem('carlos-arena-viewer',viewer)}
function getViewer(){return viewer}
const viewport=document.querySelector('#viewport');
MAP=await fetch(`${ASSET_BASE}/map.json`,{cache:'no-store'}).then(r=>r.json());
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x080b0f); scene.fog=new THREE.Fog(0x080b0f,55,125);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,250); camera.position.set(50,38,35);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.setSize(innerWidth,innerHeight); viewport.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdde5ff,0x22210f,2.1)); const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(30,70,20);scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(MAP.size.x,MAP.size.z),new THREE.MeshStandardMaterial({color:0x394038,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.set(50,0,35);scene.add(ground);
const grid=new THREE.GridHelper(100,20,0x526052,0x263026);grid.position.set(50,.02,35);grid.material.opacity=.24;grid.material.transparent=true;scene.add(grid);
const matWall=new THREE.MeshStandardMaterial({color:0x5b4636,roughness:.9}),matCover=new THREE.MeshStandardMaterial({color:0x7b6b52,roughness:.8}),matSite=new THREE.MeshStandardMaterial({color:0x8d774d,roughness:.9});
for(const [x1,z1,x2,z2] of MAP.walls){const w=x2-x1,d=z2-z1;const m=new THREE.Mesh(new THREE.BoxGeometry(Math.max(w,.5),4,Math.max(d,.5)),matWall);m.position.set((x1+x2)/2,2,(z1+z2)/2);scene.add(m)}
for(const c of MAP.cover){const m=new THREE.Mesh(new THREE.BoxGeometry(c.w,c.h,c.d),matCover);m.position.set(c.x,c.h/2,c.z);scene.add(m)}
for(const [side,p] of Object.entries(MAP.sites)){const m=new THREE.Mesh(new THREE.CylinderGeometry(5,5,.08,32),matSite);m.position.set(p.x,.06,p.z);scene.add(m);const label=makeText(side);label.position.set(p.x,5,p.z);scene.add(label)}
function makeText(text){const c=document.createElement('canvas');c.width=128;c.height=64;const x=c.getContext('2d');x.fillStyle='#fff';x.font='bold 42px sans-serif';x.textAlign='center';x.fillText(text,64,45);const t=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.scale.set(7,3.5,1);return s}
const bots={A:null,B:null};
function makeBot(side){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(1.15,1.7,6,12),new THREE.MeshStandardMaterial({color:side==='A'?0xeeeeee:0x999999,roughness:.55}));body.position.y=2;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.75,16,12),body.material);head.position.y=3.8;g.add(head);const gun=new THREE.Mesh(new THREE.BoxGeometry(.3,.3,2.4),new THREE.MeshStandardMaterial({color:0x17191c,metalness:.5}));gun.position.set(0,2.3,1.25);g.add(gun);scene.add(g);return g}
bots.A=makeBot('A');bots.B=makeBot('B');
let data=null,camMode='auto',keys={};
function setCam(mode){camMode=mode;document.querySelectorAll('#cameraBar button').forEach(b=>b.classList.toggle('active',b.dataset.cam===mode))}
document.querySelectorAll('#cameraBar button').forEach(b=>b.onclick=()=>setCam(b.dataset.cam));
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='1')setCam('auto');if(e.key==='2')setCam('A');if(e.key==='3')setCam('B');if(e.key==='4')setCam('overview')});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function updateUI(d){document.querySelector('#round').textContent=`ROUND ${d.round||1}`;document.querySelector('#score').textContent=`${d.score?.A||0} : ${d.score?.B||0}`;document.querySelector('#phase').textContent=d.status==='betting'?'APOSTAS':d.roundPhase==='break'?'INTERVALO':d.status==='finished'?'FIM':'AO VIVO';document.querySelector('#spectators').textContent=d.spectators||0;document.querySelector('#poolA').textContent=new Intl.NumberFormat('pt-BR').format(d.pool.A);document.querySelector('#poolB').textContent=new Intl.NumberFormat('pt-BR').format(d.pool.B);for(const s of ['A','B']){const f=d.fighters[s];document.querySelector('#name'+s).textContent=f.name.toUpperCase();document.querySelector('#state'+s).textContent=(f.state||'').toUpperCase();document.querySelector('#hp'+s).style.width=`${Math.max(0,f.hp/f.maxHp*100)}%`;document.querySelector('#armor'+s).textContent=`ARM ${f.armor}`;document.querySelector('#ammo'+s).textContent=`${f.ammo} / ${f.maxAmmo}`;bots[s].position.set(f.x,0,f.z);bots[s].rotation.y=f.rotation||0}document.querySelector('#timer').textContent=d.status==='betting'?fmt(d.bettingEndsAt-Date.now()):d.roundPhase==='live'?fmt(d.roundEndsAt-Date.now()):d.status==='finished'?'FINAL':'INTERVALO';document.querySelector('#betting').textContent=d.status==='betting'?'APOSTAS ABERTAS':d.status==='finished'?'ARENA ENCERRADA':`POOL ${new Intl.NumberFormat('pt-BR').format(d.pool.A+d.pool.B)}`;const lines=(d.events||[]).slice(-8).reverse();document.querySelector('#feed').innerHTML=lines.map(e=>`<div class="event">${new Date(e.at).toLocaleTimeString()} — ${escapeHtml(e.text||'')}</div>`).join('');const c=(d.commentary||[]).slice(-1)[0];if(c)document.querySelector('#commentaryText').textContent=c.text}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(ms){let s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
async function poll(){if(!id)return;try{const r=await fetch(api(),{cache:'no-store'});if(r.ok){data=await r.json();updateUI(data)}}catch{}setTimeout(poll,700)}poll();
let yaw=.8,pitch=-.28,freePos=new THREE.Vector3(50,25,35);let dragging=false,last={x:0,y:0};renderer.domElement.addEventListener('mousedown',e=>{dragging=true;last={x:e.clientX,y:e.clientY}});addEventListener('mouseup',()=>dragging=false);addEventListener('mousemove',e=>{if(!dragging)return;yaw-= (e.clientX-last.x)*.005;pitch-= (e.clientY-last.y)*.004;pitch=Math.max(-1.2,Math.min(.5,pitch));last={x:e.clientX,y:e.clientY}});
function targetFor(){if(!data)return new THREE.Vector3(50,0,35);if(camMode==='A')return bots.A.position.clone().add(new THREE.Vector3(0,2,0));if(camMode==='B')return bots.B.position.clone().add(new THREE.Vector3(0,2,0));if(camMode==='overview')return new THREE.Vector3(50,0,35);const t=data.camera?.target;return t==='A'?bots.A.position.clone().add(new THREE.Vector3(0,2,0)):t==='B'?bots.B.position.clone().add(new THREE.Vector3(0,2,0)):new THREE.Vector3(50,0,35)}
function animate(){requestAnimationFrame(animate);const t=targetFor();if(camMode==='overview'||(camMode==='auto'&&data?.camera?.target==='overview')){const desired=new THREE.Vector3(50,34,35);camera.position.lerp(desired,.035)}else if(camMode==='A'||camMode==='B'||camMode==='auto'){const desired=t.clone().add(new THREE.Vector3(-10,7,-10));camera.position.lerp(desired,.06)}else{const speed=.7;if(keys.w)freePos.z-=speed;if(keys.s)freePos.z+=speed;if(keys.a)freePos.x-=speed;if(keys.d)freePos.x+=speed;camera.position.lerp(freePos,.1)}const look=new THREE.Vector3(t.x,Math.max(1,t.y),t.z);camera.lookAt(look);renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
